[[project]]
name = "Ars Antiqua"
desc = "Software tools for analyzing, visualizing, and comparing 13th-century music"
tags = ["wip", "svelte", "typescript", "firebase", "nix"]
links = [
    {name = "website", url = "https://ars-antiqua.web.app/"},
    {name = "github", url = "https://github.com/21CSM/ars-antiqua"}
]

[[project]]
name = "Bridge"
desc = "Software tools for crowdsourcing knowledge"
tags = ["ideation", "rust", "axum", "svelte", "nix"]
links = [
    {name = "website", url = "https://bridge.zero2one.tech"},
    {name = "github", url = "https://github.com/zero2one-tech/bridge"},
]

[[project]]
name = "Gate"
desc = "Software tools for sovereign hosting"
tags = ["ideation", "rust", "tauri", "svelte", "typescript", "nix"]
links = [
    {name = "website", url = "https://gate.zero2one.tech"},
    {name = "github", url = "https://github.com/zero2one-tech/gate"},
]
